### PR TITLE
add link for image/title

### PR DESCRIPTION
**Pull request by samumist**
add link for image/title. When enabled, open a new window with the url provided. 

Tested with framework (v2.2.1) and authoring tool.

### CODE REVIEW

**Comment by samumist** [comment]
found a problem needs to be addressed.

**Comment by samumist** [comment]
when title/image is positioned in the center, the link is not working due to the `z-index` setting of the [`logo.center` class](https://github.com/deltanet/adapt-logo/blob/master/less/logo.less#L35).

**Comment by RobertPeek** [comment]
Apologies for the delay! Thanks for contributing @samumist 

Only question I have is should the "a" tag perhaps be a "button" to follow the Adapt standards?

**Comment by samumist** [comment]
Thanks for the advice @RobertPeek 
Yes, we should follow the Adpat standards which I didn't realise. 
I'll fix the code and come back.

**Pull request closed without merging**
